ITI MVC/Controllers/DepartmentController.cs
using ITI_MVC.Context;
using ITI_MVC.Interfaces;
using ITI_MVC.Models;
using ITI_MVC.CustomActionFilters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace ITI_MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    [ExceptionFilter]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentInterface Department;
        ITIContext db = new ITIContext();

        public DepartmentController(IDepartmentInterface _Department)
        {
            Department = _Department;
        }
        
        public IActionResult Index()
        {
            var depts = Department.GetAll();
            return View(depts);
        }

        public IActionResult DepartmentForm()
        {
            var depts = Department.GetAll();
            return View(depts);
        }

        
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var Courses = db.Courses.ToList();
            //Department dept = Department.GetById(id);
            Department dept = db.Departments.Include(d => d.Courses).SingleOrDefault(d => d.ID == id);
            var CoursesNotInDept = Courses.Except(dept.Courses);
            ViewBag.CoursesNotInDept = CoursesNotInDept;

            if (dept == null)
            {
                return NotFound();
            }
            else
            {
                return View(dept);
            }
        }

        public IActionResult EditCourses(int id)
        {
            var Courses = db.Courses.ToList();
            Department dept = db.Departments.Include(d => d.Courses).SingleOrDefault(d => d.ID == id);
            var CoursesNotInDept = Courses.Except(dept.Courses);
            ViewBag.CoursesNotInDept = CoursesNotInDept;

            if (dept == null)
            {
                return NotFound();
            }
            else
            {
                return View(dept);
            }
        }

        [HttpPost]
        public IActionResult EditCourses(int id, List<int> coursestoremove, List<int> coursestoadd)
        {
            var dept = db.Departments.Include(d => d.Courses).SingleOrDefault(d => d.ID == id);

            foreach (var item in coursestoremove)
            {
                var course = db.Courses.SingleOrDefault(c => c.ID == item);
                dept.Courses.Remove(course);
            }

            
            foreach (var item in coursestoadd)
            {
                var course = db.Courses.SingleOrDefault(c => c.ID == item);
                dept.Courses.Add(course);
            }

            db.SaveChanges();

            return RedirectToAction("Details", new { id = dept.ID });

        }

        public IActionResult Create(Department dept)
        {

            if (ModelState.IsValid)
            {
                Department.Add(dept);
                return RedirectToAction("Index");
            }
            else
            {
                return View("DepartmentForm", dept);
            }
        }

        [HttpPost]
        public IActionResult Update(int id, Department NewDept)
        {
            Department.Update(id, NewDept);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                var dept = Department.GetById(id);
                return View(dept);
            }
        }

        public IActionResult RemoveForm(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            Department dept = Department.GetById(id);

            if (dept == null)
            {
                return NotFound();
            }
            else
            {
                return View(dept);
            }
        }

        public IActionResult Remove(int id)
        {
            Department.Delete(id);
            return RedirectToAction("Index");
        }
    }

}

ITI MVC/Controllers/StudentController.cs
using ITI_MVC.Context;
using ITI_MVC.CustomActionFilters;
using ITI_MVC.Interfaces;
using ITI_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ITI_MVC.Controllers
{
    [Authorize(Roles = "Admin, Student")]
    [LogFilter]
    public class StudentController : Controller
    {
        private readonly IStudentInterface StudentRepo;
        private readonly IDepartmentInterface DepartmentRepo;

        public StudentController(IStudentInterface _StudentRepo, IDepartmentInterface _DepartmentRepo)
        {
            StudentRepo = _StudentRepo;
            DepartmentRepo = _DepartmentRepo;
        }

        ITIContext db = new ITIContext();

        public IActionResult Index()
        {
            var students = StudentRepo.GetAll();
            return View(students);
        }


        public IActionResult Details(int id)
        {
            Student Std = StudentRepo.GetById(id);
            if (Std == null)
            {
                return NotFound();
            }
            else
            {
                return View(Std);
            }
        }

        public IActionResult StudentForm()
        {
            var depts = DepartmentRepo.GetAll();
            SelectList sl = new(depts, "ID", "Name");
            ViewBag.depts = sl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IFormFile? stdphoto, Student std)
        {
            Guid guid = Guid.NewGuid();

            if(stdphoto != null)
            {
                string FileExtension = stdphoto.FileName.Split('.').Last();
                string FilePath = $"wwwroot/images/{guid}.{FileExtension}";
                using (FileStream st = new FileStream(FilePath, FileMode.Create))
                {
                    await stdphoto.CopyToAsync(st);
                }

                std.ImgPath = $"{guid}.{FileExtension}";
            }


            if (ModelState.IsValid)
            {
                StudentRepo.Add(std);
                return RedirectToAction("Index");
            }
            else
            {
                var depts = db.Departments.ToList();
                SelectList sl = new(depts, "ID", "Name");
                ViewBag.depts = sl;
                return View("StudentForm", std);
            }
        }

        public IActionResult CheckEmailExist(int id, string Email, string Name, string Age)
        {
            var res = db.Students.FirstOrDefault(s => s.Email == Email);
            if (res != null && res.ID != id)
            {
                return Json($"Email Already Taken. Try {Name}{Age}");
            }
            return Json(true);
        }

        public IActionResult Update(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                var depts = DepartmentRepo.GetAll();
                SelectList sl = new(depts, "ID", "Name");
                ViewBag.depts = sl;
                var std = StudentRepo.GetById(id);
                return View(std);
            }
        }
        [HttpPost]
        public IActionResult Update(int id, Student student)
        {
            StudentRepo.Update(id, student);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveForm(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            //Student std = db.Students.Include(s => s.Department).SingleOrDefault(s => s.ID == id);
            Student std = StudentRepo.GetById(id);

            if (std == null)
            {
                return NotFound();
            }
            else
            {
                return View(std);
            }
        }

        public IActionResult Remove(int id)
        {
            StudentRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ITI MVC/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_MVC.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ReadArray()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ReadArray(string[] arr, IFormFile stdphoto)
        {
            Guid guid = Guid.NewGuid();
            string FileExtension = stdphoto.FileName.Split('.').Last();
            string FilePath = $"wwwroot/images/{guid}.{FileExtension}";



            using (FileStream st = new FileStream(FilePath, FileMode.Create))
            {
                await stdphoto.CopyToAsync(st);
            }

            string s = "";

            foreach (var item in arr)
            {
                s += item;
            }
            
            ViewBag.image = $"{guid}.{FileExtension}";

            return View("imgView");

        }

        public IActionResult ReadDic(Dictionary<string, int> arr) 
        {

            return View();
        }

        public IActionResult AddData(int id, string Name)
        {

            HttpContext.Session.SetInt32("id", id);
            HttpContext.Session.SetString("name", Name);
            CookieOptions cookie = new CookieOptions() { Expires=DateTime.Now.AddMinutes(1)};
            Response.Cookies.Append("sid", id.ToString(), cookie);
            Response.Cookies.Append("sname", Name);
            return Content($"{id} :: {Name}");
        }

        public IActionResult ReadData()
        {
            //int? id = HttpContext.Session.GetInt32("id");
            //string Name = HttpContext.Session.GetString("name");
            int id = int.Parse(Request.Cookies["sid"]);
            string Name = Request.Cookies["sname"];
            return Content($"{id} :: {Name}");
        }
    }
}

ITI MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ITI MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ITI_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="ReadArray">Test</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ITI MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>